### ISSUE TITLE
A question about hosting

### ISSUE THREAD

**Issue by favna** [atlas44/web-fusee-launcher#1]
In the readme you say that the connection has to be over HTTPS, but wouldn't it also work when hosting the site locally through, for example, expressJS? If it does then I'd say it is worth adding an expressJS `server.js` file as well as a `package.json` with the proper configuration. 

The latter ofc is assuming you have some basic NodeJs knowledge or don't mind learning it

**Comment by keysmashes** [comment]
I can't try it right now, but it appears to also work when loaded from the local filesystem (the WebUSB permission prompt appears), so a web server might not even be necessary.

**Comment by favna** [comment]
I'm in the same boat for not being to test. I want to be careful with my device and if anything I want to wait until this summer when I should be getting a 3D printer to print one of those things to easily short the pins

**Comment by omgmog** [comment]
You could easily host this on [Github pages](https://pages.github.com/) and get free HTTPS. Heck, @atlas44 could simply turn on Pages support for this repo and then this whole script would just work immediately via https://atlas44.github.io/web-fusee-launcher
